name: Update Website

on:
  workflow_call:

jobs:
  update_website:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger website update
      if: ${{ github.repository_owner == 'xemu-project' }}
      uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 # v1.3.1
      with:
        workflow: build.yml
        repo: xemu-project/xemu-website
        token: ${{ secrets.XEMU_ROBOT_TOKEN }}
        ref: master
